#
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
#
# This file is regenerated from harbour-moji.yaml by mb2 at build time, so
# the yaml is the source of truth. It is kept in the repository so the
# packaging can be read without running the Sailfish SDK: keep the two in
# sync when editing the yaml.
#

Name:       harbour-moji

# >> macros
# << macros

Summary:    Moji OCR - read text from photos, offline
Version:    0.1.0
Release:    1
Group:      Qt/Qt
License:    GPLv2+ (binary, via Poppler) / MIT (code) / Apache-2.0 (Tesseract and its language data)
URL:        https://github.com/nicosouv/harbour-moji
Source0:    %{name}-%{version}.tar.bz2
Source100:  harbour-moji.yaml
Requires:   sailfishsilica-qt5 >= 0.10.9
Requires:   qt5-qtdeclarative-import-multimedia
Requires:   poppler-qt5
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Gui)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(Qt5Concurrent)
BuildRequires:  pkgconfig(Qt5Sql)
BuildRequires:  pkgconfig(poppler-qt5)
BuildRequires:  qt5-qttools-linguist
BuildRequires:  cmake
BuildRequires:  desktop-file-utils

%description
Reads text from photos, entirely on the device.

Moji has no network permission at all. The Sailjail sandbox refuses every
outbound connection, so "works offline" is enforced by the system rather
than promised by the developer. There is no account, no telemetry and no
model to download at first run: the language data is inside the package.

Features:
- 30 recognition languages built in, including Arabic, Hebrew, Chinese,
  Japanese, Korean, Hindi, Thai and Vietnamese
- Reads several languages at once, for documents that mix them
- Raw text, or tap a word in the photo to take out its line or paragraph
- IBANs, card numbers, ISBNs and passport codes checked against their own
  checksums, so a digit the camera misread is caught rather than copied
- Interface in English and French
- webOS-inspired interface, with a Sailfish ambience theme


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%cmake

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}
%{_datadir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/*/apps/%{name}.png
%{_libdir}/%{name}/*.so*
# >> files
# << files
